sudo: required

services:
  - docker

env:
  - FISH_REPO=nightly:/master
  - FISH_REPO=release:/2

before_install:  
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine

install:
  - docker build --build-arg=fish_repo="$FISH_REPO" -t fry .

script:
  - docker run --rm -it fry make test
